<dl>
          <dt class="fl"><a href="[field:arcurl/]" title="[field:title/]"> <img alt="[field:title/]" _src="[field:picname/]" width="224" height="174" /></a></dt>
          <dd>
            <h5> <a href="[field:arcurl/]" title="[field:title/]"> [field:title/]</a></h5>
            <p> <br/>
              [field:info/]...</p>
            <a class="btnGd" href="[field:arcurl/]">查看更多</a> </dd>
        </dl>