<?php
$z[0]=Array("field","",497,516);
$z[0][4]['name']="title";
$z[1]=Array("global","",517,543);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",584,606);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",646,697);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",843,880);
$z[4][4]['filename']="head_m.htm";
$z[5]=Array("channel","\r\n	\r\n	<a href='list.php?tid=[field:id/]'>[field:typename/]</a>\r\n	\r\n	",1001,1192);
$z[5][4]['type']="son";
$z[5][4]['row']="20";
$z[5][4]['currentstyle']="<a class='now' href='~typelink~' ~rel~>~typename~</a></li>";
$z[6]=Array("field","",1242,1261);
$z[6][4]['name']="title";
$z[7]=Array("field","",1273,1291);
$z[7][4]['name']="body";
$z[8]=Array("include","",1373,1410);
$z[8][4]['filename']="foot_m.htm";

?>