<dl class="alCont fr">
        <dt class="fl"><a href="[field:arcurl/]" title="[field:title/]"> <img src="[field:picname/]" alt="[field:title/]" width="380" height="330" /></a></dt>
        <dd>
          <h5> <a href="[field:arcurl/]" title="[field:title/]">案例名称：[field:title/]</a></h5>
          <p> [field:info/]...</p>
          <a class="gyMore" href="[field:arcurl/]">查看更多</a> </dd>
      </dl>