<?php
$z[0]=Array("flink","  [field:link /]  ",222,300);
$z[0][4]['titlelen']="20";
$z[0][4]['row']="20";
$z[0][4]['type']="text";
$z[1]=Array("type"," <a href=\"[field:typelink/]\">[field:typename/]</a> ",390,475);
$z[1][4]['typeid']="1";
$z[2]=Array("type"," <a href=\"[field:typelink/]\">[field:typename/]</a> ",485,571);
$z[2][4]['typeid']="13";
$z[3]=Array("type"," <a href=\"[field:typelink/]\">[field:typename/]</a> ",581,667);
$z[3][4]['typeid']="27";
$z[4]=Array("type"," <a href=\"[field:typelink/]\">[field:typename/]</a> ",677,763);
$z[4][4]['typeid']="39";
$z[5]=Array("type"," <a href=\"[field:typelink/]\">[field:typename/]</a> ",773,859);
$z[5][4]['typeid']="28";
$z[6]=Array("type"," <a href=\"[field:typelink/]\">[field:typename/]</a> ",869,955);
$z[6][4]['typeid']="24";
$z[7]=Array("type"," <a href=\"[field:typelink/]\">[field:typename/]</a> ",965,1051);
$z[7][4]['typeid']="34";
$z[8]=Array("type"," <a href=\"[field:typelink/]\">[field:typename/]</a> ",1061,1147);
$z[8][4]['typeid']="26";
$z[9]=Array("global","",1295,1321);
$z[9][4]['name']="cfg_powerby";
$z[10]=Array("global","",1423,1447);
$z[10][4]['name']="cfg_beian";
$z[11]=Array("global","",1680,1702);
$z[11][4]['name']="cfg_tel";

?>