<?php
$z[0]=Array("global","",769,796);
$z[0][4]['name']="cfg_dwebname";
$z[1]=Array("type","<a href=\"[field:typeurl/]\">[field:typename/]</a>",823,906);
$z[1][4]['typeid']="24";
$z[2]=Array("type","<a href=\"[field:typeurl/]\">[field:typename/]</a>",909,992);
$z[2][4]['typeid']="45";
$z[3]=Array("global","",1003,1030);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("global","",1215,1241);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",1292,1317);
$z[5][4]['name']="cfg_biaoyu";
$z[6]=Array("global","",1430,1452);
$z[6][4]['name']="cfg_tel";
$z[7]=Array("channel","\r\n      <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n     ",1611,1810);
$z[7][4]['type']="top";
$z[7][4]['row']="9";
$z[7][4]['currentstyle']="<li><a class='cur' href='~typelink~' ~rel~>~typename~</a></li>";

?>