<?php
$z[0]=Array("global","",104,131);
$z[0][4]['name']="cfg_dwebname";
$z[1]=Array("type","<a href=\"[field:typeurl/]\">[field:typename/]</a>",158,241);
$z[1][4]['typeid']="24";
$z[2]=Array("type","<a href=\"[field:typeurl/]\">[field:typename/]</a>",244,327);
$z[2][4]['typeid']="26";
$z[3]=Array("global","",487,513);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",564,589);
$z[4][4]['name']="cfg_biaoyu";
$z[5]=Array("global","",702,724);
$z[5][4]['name']="cfg_tel";
$z[6]=Array("channel","\r\n      <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n     ",887,1008);
$z[6][4]['type']="top";
$z[6][4]['row']="9";

?>