<?php
$z[0]=Array("global","",193,220);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",223,249);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",559,585);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",800,822);
$z[3][4]['name']="cfg_tel";
$z[4]=Array("type","\r\n      <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n      ",973,1081);
$z[4][4]['typeid']="5";
$z[5]=Array("type","\r\n      <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n      ",1089,1197);
$z[5][4]['typeid']="3";
$z[6]=Array("type","\r\n      <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n      ",1205,1313);
$z[6][4]['typeid']="4";
$z[7]=Array("type","\r\n      <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n      ",1321,1429);
$z[7][4]['typeid']="1";
$z[8]=Array("type","\r\n      <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n      ",1437,1546);
$z[8][4]['typeid']="13";
$z[9]=Array("type","\r\n      <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n      ",1554,1663);
$z[9][4]['typeid']="27";
$z[10]=Array("type","\r\n      <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n      ",1671,1780);
$z[10][4]['typeid']="28";
$z[11]=Array("type","\r\n      <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n      ",1788,1897);
$z[11][4]['typeid']="24";
$z[12]=Array("type","\r\n      <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n      ",1905,2014);
$z[12][4]['typeid']="34";
$z[13]=Array("type","\r\n      <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n      ",2022,2131);
$z[13][4]['typeid']="26";

?>