<?php
$z[0]=Array("global","",104,131);
$z[0][4]['name']="cfg_dwebname";
$z[1]=Array("type","<a href=\"[field:typeurl/]\">[field:typename/]</a>",158,241);
$z[1][4]['typeid']="24";
$z[2]=Array("type","<a href=\"[field:typeurl/]\">[field:typename/]</a>",244,327);
$z[2][4]['typeid']="45";
$z[3]=Array("global","",338,365);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("global","",550,576);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",627,652);
$z[5][4]['name']="cfg_biaoyu";
$z[6]=Array("global","",765,787);
$z[6][4]['name']="cfg_tel";
$z[7]=Array("channel","\r\n      <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n     ",946,1145);
$z[7][4]['type']="top";
$z[7][4]['row']="9";
$z[7][4]['currentstyle']="<li><a class='cur' href='~typelink~' ~rel~>~typename~</a></li>";

?>