<?php
$z[0]=Array("field","",75,134);
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopTypename(@me)";
$z[1]=Array("channel","\r\n      <li sid='0001,0011'><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      ",187,422);
$z[1][4]['type']="son";
$z[1][4]['currentstyle']="<li class='cur'><a href='~typelink~' class='thisclass'>~typename~</a></li>";
$z[2]=Array("global","",442,466);
$z[2][4]['name']="cfg_telby";
$z[3]=Array("global","",550,572);
$z[3][4]['name']="cfg_tel";
$z[4]=Array("arclist","\r\n<li><a href='[field:arcurl/]' title='[field:title/]'>[field:title/]</a></li>\r\n",674,814);
$z[4][4]['titlelen']="60";
$z[4][4]['row']="10";
$z[4][4]['typeid']="34";
$z[5]=Array("type","<a class=\"yan2\" href=\"[field:typeurl/]\">[field:typename/]</a>",920,1016);
$z[5][4]['typeid']="45";
$z[6]=Array("global","",1097,1122);
$z[6][4]['name']="cfg_lianxi";

?>