<?php
$z[0]=Array("field","",277,306);
$z[0][4]['name']="typename";
$z[1]=Array("global","",307,333);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",378,407);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",451,509);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1220,1255);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",1470,1505);
$z[5][4]['filename']="left.htm";
$z[6]=Array("field","",1590,1619);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n        <dl class=\"dl_pro3\">\r\n              <dt><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\"> <img  src=\"[field:picname/]\" alt=\"[field:title/]\" /></a></dt>\r\n              <dd>\r\n            <h4> <a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\"> [field:title/]</a></h4>\r\n          </dd>\r\n            </dl>\r\n        ",1726,2113);
$z[7][4]['pagesize']="6";
$z[8]=Array("pagelist","",2331,2385);
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[9]=Array("arclist","\r\n        <dl class=\"product_dl_commend\">\r\n              <dt><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\"> <img src=\"[field:picname/]\" alt=\"[field:title/]\" /></a></dt>\r\n              <dd> <a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\"> [field:title/]</a></dd>\r\n            </dl>\r\n        ",2618,2990);
$z[9][4]['row']="4";
$z[9][4]['typeid']="1";
$z[10]=Array("include","",3189,3226);
$z[10][4]['filename']="footer.htm";

?>