<?php
$z[0]=Array("field","",497,526);
$z[0][4]['name']="typename";
$z[1]=Array("global","",527,553);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",594,623);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",663,721);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",869,906);
$z[4][4]['filename']="head_m.htm";
$z[5]=Array("channel","\r\n	\r\n	<a href='list.php?tid=[field:id/]'>[field:typename/]</a>\r\n	\r\n	",1024,1215);
$z[5][4]['type']="son";
$z[5][4]['row']="20";
$z[5][4]['currentstyle']="<a class='now' href='~typelink~' ~rel~>~typename~</a></li>";
$z[6]=Array("list","\r\n       <li><a href=\"javascript:void(0)\"><div class=\"lzj\"><img src=\"[field:litpic/]\"/></div>[field:title/]</a></li>\r\n       ",1305,1480);
$z[6][4]['pagesize']="9";
$z[6][4]['titlelen']="16";
$z[7]=Array("pagelist","",1592,1649);
$z[7][4]['listitem']="index,end,pageno";
$z[7][4]['listsize']="1";
$z[8]=Array("include","",1727,1764);
$z[8][4]['filename']="foot_m.htm";

?>