<?php
$z[0]=Array("global","",204,230);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",271,300);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",340,398);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",1131,1166);
$z[3][4]['filename']="head.htm";
$z[4]=Array("global","",1339,1394);
$z[4][4]['name']="keyword";
$z[4][4]['function']="RemoveXSS(@me)";
$z[5]=Array("list","\r\n        <dl class=\"sear_dl\" style=\"width: 95%;\">\r\n          <dt class=\"tit\"><a target=\"_blank\" href=\"[field:arcurl/]\"\r\n                                    class=\"tit_a\">[[field:typename/]][field:title/]</a><span class=\"f11\">[\r\n            [field:stime/]\r\n            ]</span></dt>\r\n          <dd class=\"d1\"> <font color='red'>[field:description/]...</dd>\r\n        </dl>\r\n        ",1486,1903);
$z[5][4]['perpage']="20";
$z[6]=Array("likewords","",2063,2088);
$z[6][4]['num']="8";
$z[7]=Array("pagelist","",2337,2391);
$z[7][4]['listitem']="index,end,pre,next,pageno";
$z[8]=Array("channel","\r\n        <li> <img src=\"/skin/images/sico15.gif\" alt=\"\" title=\"\" /><a\r\n                                    href=\"[field:typelink/]\" title=\"\"> [field:typename/]</a></li>\r\n       ",2698,2936);
$z[8][4]['type']="son";
$z[8][4]['row']="20";
$z[8][4]['typeid']="1";
$z[9]=Array("include","",3089,3126);
$z[9][4]['filename']="footer.htm";

?>